### ISSUE TITLE
Issue about using WD classifier and running test.py

### ISSUE THREAD

**Issue by SafiaBahria** [luizgh/sigver#12]
Hello,
I am a Phd scholar and I am working on signarure verification. I am trying ti execute your code and want to see how you have computed the EER for all the runs/folds of data. When i run test.py in wd folder i get the following error.
usage: test.py [-h] -m {signet,signet_thin,signet_smaller} --model-path
               MODEL_PATH --data-path DATA_PATH [--save-path SAVE_PATH]
               [--input-size INPUT_SIZE INPUT_SIZE]
               [--exp-users EXP_USERS EXP_USERS]
               [--dev-users DEV_USERS DEV_USERS] [--gen-for-test GEN_FOR_TEST]
               [--forg-from_exp FORG_FROM_EXP] [--forg-from_dev FORG_FROM_DEV]
               [--svm-type {rbf,linear}] [--svm-c SVM_C]
               [--svm-gamma SVM_GAMMA] [--gpu-idx GPU_IDX]
               [--batch-size BATCH_SIZE] [--folds FOLDS]
test.py: error: the following arguments are required: -m, --model-path, --data-path
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
Can you please guied me what is the solution of this. Moreover I want to use your eer_user_threshold function in my own implementation. Fot that I need to compute eer for each user and then compute overall EER for each fold/run???

**Comment by luizgh** [comment]
Hello @SafiaBahria . Please see the Readme (https://github.com/luizgh/sigver/blob/master/README.md) for an example of how to run the system. For the test, you need both a trained model (e.g. one of the models I trained on GPDS) and a dataset.
