### ISSUE TITLE
Problem about the result pickle file 

### ISSUE THREAD

**Issue by LeePin-Git** [luizgh/sigver#4]
As a beginner of Python, I want to ask 
How can the pickle file be transformed to a readable format to obtain the FAR, AUC, owner prediction and etc?

**Comment by luizgh** [comment]
@LeePin-Git you can find examples of how to load pickle files here: https://wiki.python.org/moin/UsingPickle. 

The structure of the result can be found here: https://github.com/luizgh/sigver/blob/master/README.md#training-wd-classifiers-and-evaluating-the-result. It already contains metrics such as FAR, FRR, AUC. It also has all predictions, so you can generate any metrics you want from them.

**Comment by LeePin-Git** [comment]
Thank you very much for your respond ! It really helps me



    Luiz Gustavo Hafemann (<notifications@github.com>) 在 2019年5月13日星期一 下午9:23:28 [GMT+8] 寫道：  
 
 
@LeePin-Git you can find examples of how to load pickle files here: https://wiki.python.org/moin/UsingPickle.

The structure of the result can be found here: https://github.com/luizgh/sigver/blob/master/README.md#training-wd-classifiers-and-evaluating-the-result. It already contains metrics such as FAR, FRR, AUC. It also has all predictions, so you can generate any metrics you want from them.
